-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) AS TOTAL_SALES FROM BOOK b
INNER JOIN AUTHOR a
ON a.AUTHOR_ID = b.AUTHOR_ID
INNER JOIN BOOK_SALES s
ON b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;