-- 코드를 입력하세요
SELECT DATE_FORMAT(s.SALES_DATE, '%Y') AS YEAR, DATE_FORMAT(s.SALES_DATE, '%m') AS MONTH, i.GENDER, COUNT(DiSTINCT s.USER_ID) AS USERS FROM ONLINE_SALE s
INNER JOIN USER_INFO i
ON s.USER_ID = i.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, i.GENDER
ORDER BY YEAR ASC, MONTH ASC, i.GENDER ASC;